// shared/http/errorCodes.js
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MODULE_TIMEOUT: 'MODULE_TIMEOUT',
  MODULE_FAILURE: 'MODULE_FAILURE',
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  LLM_LOCATION_UNSUPPORTED: 'LLM_LOCATION_UNSUPPORTED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SUCCESS: 'SUCCESS',
  PARTIAL_SUCCESS: 'PARTIAL_SUCCESS',
};
